<a href="https://colab.research.google.com/github/kidrah-git/-Data-Visualisation-/blob/Visulatization/_fundamentals_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import tenorflow
import tensorflow as tf
print(tf. __version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of deimension of a tensor
scalar.ndim


0

In [ ]:
#creating a vector
vector = tf.constant ([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of the vector
vector.ndim

1

In [ ]:
# create a Matrix
matrix = tf.constant ([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# specify the data type
another_matrix = tf.constant ([[10., 5.], [5., 10.], [7., 10.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 5., 10.],
       [ 7., 10.]], dtype=float16)>

In [ ]:
# whats the number of dimension of another matrix
another_matrix.ndim

2

In [ ]:
# lets create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [2, 3, 4 ],
                      [ 5, 6, 7],
                      [3, 4, 6],
                       [2, 3, 5],
                       [4, 6, 7]]])
tensor

<tf.Tensor: shape=(1, 6, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7],
        [3, 4, 6],
        [2, 3, 5],
        [4, 6, 7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#creating tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changeable_tensor, unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# how about creating the changable tensor into .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# creating random tensors
# creating two random with the same tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproductibility
random_1 = random_1.normal (shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal (shape=(3,2))

# are random_1 and random_2 equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
### shuffle the order of the elements in the tensor


not_shuffle = tf.constant ([[10,  6], [7, 10], [5, 3]])





In [ ]:
# shuffle our non shuffled tenors
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 5,  3],
       [10,  6]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  6],
       [ 7, 10],
       [ 5,  3]], dtype=int32)>

In [ ]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  6],
       [ 7, 10],
       [ 5,  3]], dtype=int32)>

In [ ]:
## Creating tensors of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# creating tensors of all zero
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#you can also trun numnpy array into tensors

the main diff between numpy arrays and tensor flow is that tensors can run in gpu much faster for numeric computing





In [ ]:

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #creating a numpy array between 1 and 25
numpy_A
# x = tf.constant (some _matrix) #capital for matrix or tensor
#y = tf.constant (vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A , shape = (3, 8))
B = tf.constant( numpy_A)
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
2 * 3 * 4

24

In [ ]:
#

## Getting information from tenors
when dealing with tensors you probaly want to be aware of the following ttributes:
*shape
*rank
*Axix or dimensions
*size

In [ ]:
#creating a rank 4 tensor (4 dimensions )
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# rank 4 tensor with zero element
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#get various attribute of our tensor
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimension (rank): ",rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Element along the 0 axix: ",rank_4_tensor.shape[0])
print("Element along the last Axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor))
print("Total number of elements in our tenosr: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimension (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Element along the 0 axix:  2
Element along the last Axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tenosr:  120


## indexing the Tensors
tensors can be index just like python list


In [ ]:
some_list =  [1, 2, 3 ,4]
some_list[2:]

[3, 4]

In [ ]:
# get first two element of each two tensors
rank_4_tensor[:2, :2, : 2 , :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first elemnent in each dimension from each index exce[t ]

rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
#create a rang two tensor of 2dimension
rank_2_tensor = tf.constant([10, 7],  shape=[2])
print (rank_2_tensor)

tf.Tensor([10  7], shape=(2,), dtype=int32)
