<a href="https://colab.research.google.com/github/kidrah-git/-Data-Visualisation-/blob/Visulatization/hardik_week5_Simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
sentences = ["I feel joyful today", "This meal is unpleasant", "One day, we are destined to succeed", "That movie was terrible", "The cost was exorbitant", "I dislike crocodiles", "It was a brilliant idea", "We reached the peak of the tallest mountain", "Offering support to those in need is crucial", "Stock prices are expected to increase next month", "I'm in a cheerful mood today", "The food lacks good flavor", "Our perseverance will pay off eventually", "Watching that film was disappointing", "The price felt overly high", "Crocodiles are not my favorite", "That idea turned out to be amazing", "We successfully scaled the highest summit", "Helping the less fortunate is our responsibility", "The stock market might experience a rise next month"]

In [4]:
label = [1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1]

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [7]:
tokens = Tokenizer(oov_token = 'oov')
tokens.fit_on_texts(sentences)

In [8]:
vocab = tokens.word_index

In [9]:
vocab

{'oov': 1,
 'the': 2,
 'to': 3,
 'was': 4,
 'is': 5,
 'we': 6,
 'are': 7,
 'that': 8,
 'a': 9,
 'i': 10,
 'today': 11,
 'crocodiles': 12,
 'idea': 13,
 'in': 14,
 'stock': 15,
 'next': 16,
 'month': 17,
 'our': 18,
 'feel': 19,
 'joyful': 20,
 'this': 21,
 'meal': 22,
 'unpleasant': 23,
 'one': 24,
 'day': 25,
 'destined': 26,
 'succeed': 27,
 'movie': 28,
 'terrible': 29,
 'cost': 30,
 'exorbitant': 31,
 'dislike': 32,
 'it': 33,
 'brilliant': 34,
 'reached': 35,
 'peak': 36,
 'of': 37,
 'tallest': 38,
 'mountain': 39,
 'offering': 40,
 'support': 41,
 'those': 42,
 'need': 43,
 'crucial': 44,
 'prices': 45,
 'expected': 46,
 'increase': 47,
 "i'm": 48,
 'cheerful': 49,
 'mood': 50,
 'food': 51,
 'lacks': 52,
 'good': 53,
 'flavor': 54,
 'perseverance': 55,
 'will': 56,
 'pay': 57,
 'off': 58,
 'eventually': 59,
 'watching': 60,
 'film': 61,
 'disappointing': 62,
 'price': 63,
 'felt': 64,
 'overly': 65,
 'high': 66,
 'not': 67,
 'my': 68,
 'favorite': 69,
 'turned': 70,
 'out': 71,
 

In [10]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequence = tokenizer.texts_to_sequences(sentences)

print(sequence )

[[9, 18, 19, 10], [20, 21, 4, 22], [23, 24, 5, 6, 25, 2, 26], [7, 27, 3, 28], [1, 29, 3, 30], [9, 31, 11], [32, 3, 8, 33, 12], [5, 34, 1, 35, 36, 1, 37, 38], [39, 40, 2, 41, 13, 42, 4, 43], [14, 44, 6, 45, 2, 46, 15, 16], [47, 13, 8, 48, 49, 10], [1, 50, 51, 52, 53], [17, 54, 55, 56, 57, 58], [59, 7, 60, 3, 61], [1, 62, 63, 64, 65], [11, 6, 66, 67, 68], [7, 12, 69, 70, 2, 71, 72], [5, 73, 74, 1, 75, 76], [77, 1, 78, 79, 4, 17, 80], [1, 14, 81, 82, 83, 8, 84, 15, 16]]


In [11]:
print(tokenizer.word_index)

{'the': 1, 'to': 2, 'was': 3, 'is': 4, 'we': 5, 'are': 6, 'that': 7, 'a': 8, 'i': 9, 'today': 10, 'crocodiles': 11, 'idea': 12, 'in': 13, 'stock': 14, 'next': 15, 'month': 16, 'our': 17, 'feel': 18, 'joyful': 19, 'this': 20, 'meal': 21, 'unpleasant': 22, 'one': 23, 'day': 24, 'destined': 25, 'succeed': 26, 'movie': 27, 'terrible': 28, 'cost': 29, 'exorbitant': 30, 'dislike': 31, 'it': 32, 'brilliant': 33, 'reached': 34, 'peak': 35, 'of': 36, 'tallest': 37, 'mountain': 38, 'offering': 39, 'support': 40, 'those': 41, 'need': 42, 'crucial': 43, 'prices': 44, 'expected': 45, 'increase': 46, "i'm": 47, 'cheerful': 48, 'mood': 49, 'food': 50, 'lacks': 51, 'good': 52, 'flavor': 53, 'perseverance': 54, 'will': 55, 'pay': 56, 'off': 57, 'eventually': 58, 'watching': 59, 'film': 60, 'disappointing': 61, 'price': 62, 'felt': 63, 'overly': 64, 'high': 65, 'not': 66, 'my': 67, 'favorite': 68, 'turned': 69, 'out': 70, 'be': 71, 'amazing': 72, 'successfully': 73, 'scaled': 74, 'highest': 75, 'summit'

In [12]:
 from tensorflow.keras.preprocessing.sequence import pad_sequences

 sequence= pad_sequences (sequence,maxlen=6, padding='post', truncating='post')

 print (sequence)


[[ 9 18 19 10  0  0]
 [20 21  4 22  0  0]
 [23 24  5  6 25  2]
 [ 7 27  3 28  0  0]
 [ 1 29  3 30  0  0]
 [ 9 31 11  0  0  0]
 [32  3  8 33 12  0]
 [ 5 34  1 35 36  1]
 [39 40  2 41 13 42]
 [14 44  6 45  2 46]
 [47 13  8 48 49 10]
 [ 1 50 51 52 53  0]
 [17 54 55 56 57 58]
 [59  7 60  3 61  0]
 [ 1 62 63 64 65  0]
 [11  6 66 67 68  0]
 [ 7 12 69 70  2 71]
 [ 5 73 74  1 75 76]
 [77  1 78 79  4 17]
 [ 1 14 81 82 83  8]]


In [13]:
sequence = tokens.texts_to_sequences(sentences)

In [14]:
sequence

[[10, 19, 20, 11],
 [21, 22, 5, 23],
 [24, 25, 6, 7, 26, 3, 27],
 [8, 28, 4, 29],
 [2, 30, 4, 31],
 [10, 32, 12],
 [33, 4, 9, 34, 13],
 [6, 35, 2, 36, 37, 2, 38, 39],
 [40, 41, 3, 42, 14, 43, 5, 44],
 [15, 45, 7, 46, 3, 47, 16, 17],
 [48, 14, 9, 49, 50, 11],
 [2, 51, 52, 53, 54],
 [18, 55, 56, 57, 58, 59],
 [60, 8, 61, 4, 62],
 [2, 63, 64, 65, 66],
 [12, 7, 67, 68, 69],
 [8, 13, 70, 71, 3, 72, 73],
 [6, 74, 75, 2, 76, 77],
 [78, 2, 79, 80, 5, 18, 81],
 [2, 15, 82, 83, 84, 9, 85, 16, 17]]

In [15]:
sequences = pad_sequences(sequence, maxlen=6, padding = 'post', truncating='post')

In [16]:
sequences

array([[10, 19, 20, 11,  0,  0],
       [21, 22,  5, 23,  0,  0],
       [24, 25,  6,  7, 26,  3],
       [ 8, 28,  4, 29,  0,  0],
       [ 2, 30,  4, 31,  0,  0],
       [10, 32, 12,  0,  0,  0],
       [33,  4,  9, 34, 13,  0],
       [ 6, 35,  2, 36, 37,  2],
       [40, 41,  3, 42, 14, 43],
       [15, 45,  7, 46,  3, 47],
       [48, 14,  9, 49, 50, 11],
       [ 2, 51, 52, 53, 54,  0],
       [18, 55, 56, 57, 58, 59],
       [60,  8, 61,  4, 62,  0],
       [ 2, 63, 64, 65, 66,  0],
       [12,  7, 67, 68, 69,  0],
       [ 8, 13, 70, 71,  3, 72],
       [ 6, 74, 75,  2, 76, 77],
       [78,  2, 79, 80,  5, 18],
       [ 2, 15, 82, 83, 84,  9]], dtype=int32)

In [17]:
sequences.shape

(20, 6)

In [18]:
 sequences.shape[0]

20

In [19]:
label = np.array(label).reshape(-1)

In [20]:
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense

In [21]:
model = Sequential()

In [22]:
model.add(SimpleRNN(1, input_shape=(sequences.shape[1],1), activation = 'relu' ))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [23]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [24]:
model.fit(sequences, label, epochs=7)

Epoch 1/7
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.8000 - loss: 0.4738
Epoch 2/7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.7000 - loss: 0.4734
Epoch 3/7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8000 - loss: 0.4731
Epoch 4/7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8000 - loss: 0.4728
Epoch 5/7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8000 - loss: 0.4726
Epoch 6/7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8000 - loss: 0.4724
Epoch 7/7
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8000 - loss: 0.4722


In [25]:
test = ['He lives in Italy']

In [26]:
# tokens.fit_on_texts(test)

In [27]:
test = tokens.texts_to_sequences(test)

In [28]:
test = pad_sequences(test, padding = 'post', truncating = 'post', maxlen = 6)

In [29]:
test

array([[ 1,  1, 14,  1,  0,  0]], dtype=int32)

In [30]:
test.shape

(1, 6)

In [31]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[0.4982501]], dtype=float32)

In [32]:
tokens.word_index

{'oov': 1,
 'the': 2,
 'to': 3,
 'was': 4,
 'is': 5,
 'we': 6,
 'are': 7,
 'that': 8,
 'a': 9,
 'i': 10,
 'today': 11,
 'crocodiles': 12,
 'idea': 13,
 'in': 14,
 'stock': 15,
 'next': 16,
 'month': 17,
 'our': 18,
 'feel': 19,
 'joyful': 20,
 'this': 21,
 'meal': 22,
 'unpleasant': 23,
 'one': 24,
 'day': 25,
 'destined': 26,
 'succeed': 27,
 'movie': 28,
 'terrible': 29,
 'cost': 30,
 'exorbitant': 31,
 'dislike': 32,
 'it': 33,
 'brilliant': 34,
 'reached': 35,
 'peak': 36,
 'of': 37,
 'tallest': 38,
 'mountain': 39,
 'offering': 40,
 'support': 41,
 'those': 42,
 'need': 43,
 'crucial': 44,
 'prices': 45,
 'expected': 46,
 'increase': 47,
 "i'm": 48,
 'cheerful': 49,
 'mood': 50,
 'food': 51,
 'lacks': 52,
 'good': 53,
 'flavor': 54,
 'perseverance': 55,
 'will': 56,
 'pay': 57,
 'off': 58,
 'eventually': 59,
 'watching': 60,
 'film': 61,
 'disappointing': 62,
 'price': 63,
 'felt': 64,
 'overly': 65,
 'high': 66,
 'not': 67,
 'my': 68,
 'favorite': 69,
 'turned': 70,
 'out': 71,
 